apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgreesdb
spec:
  selector:
    matchLabels:
      app: postgreesdb
  template:
    metadata:
      labels:
        app: postgreesdb
    spec:
      containers:
      - name: postgreesdb
        image: postgres:10.4
        env:
          - name: POSTGRES_DB
            value: "db" 
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"                   
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgreesdb-service
spec:
  selector:
    app: postgreesdb
  ports:
  - port: 5432        
    targetPort: 5432